# Generated by Django 2.1.7 on 2019-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_02', '0004_remove_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default='2015-11-11'),
            preserve_default=False,
        ),
    ]
